name: twilio_programmable_voice
description: Non-official Flutter Twilio API for Twilio Programmable Voice Resource
version: 0.0.0-dev.1
homepage:
repository: https://github.com/Bilik-fr/twilio_programmable_voice/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.3.0 # https://pub.dev/packages/permission_handler
  soundpool: ^2.2.0
  firebase_messaging: ^11.2.0
  firebase_core: ^1.10.2
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: fr.izio.twilio_programmable_voice
        pluginClass: TwilioProgrammableVoicePlugin
      ios:
        pluginClass: SwiftTwilioProgrammableVoicePlugin
  assets:
    - packages/twilio_programmable_voice/assets/sounds/disconnect.wav
    - packages/twilio_programmable_voice/assets/sounds/incoming.wav
    - packages/twilio_programmable_voice/assets/sounds/outgoing.wav
